ALTER TABLE tabs ADD COLUMN creator TEXT;
ALTER TABLE tabs ADD COLUMN creator_avatar TEXT;
ALTER TABLE tabs ADD COLUMN creator_url TEXT;
ALTER TABLE tabs ADD COLUMN published_at TEXT;
ALTER TABLE tabs ADD COLUMN tags TEXT;
ALTER TABLE tabs ADD COLUMN deleted_at TEXT;
ALTER TABLE tabs ADD COLUMN starred INTEGER DEFAULT 0;
